config/routes.rb
Rails.application.routes.draw do
	root to: "static_pages#root"
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  namespace :api, defaults: {format: :json} do
  	resources :ice_creams
  	resources :reviews, only: [:create, :show]
  	resources :refrigeratings, only: [:create, :destroy, :show]
  	resources :users
  	resources :creameries, only: [:create]
  end
end

app/models/creamery.rb
class Creamery < ActiveRecord::Base
	has_many :ice_creams
end

app/models/ice_cream.rb
class IceCream < ActiveRecord::Base

	validates :flavor, :creamery_id, presence: true

	has_many :reviews

	has_many(
		:reviewers,
		through: :reviews,
		source: :user
	)

	has_many :refrigeratings

	has_many(
		:fans,
		through: :refrigeratings,
		source: :user
	)

	belongs_to :creamery

	def average_rating
		if self.reviews.size == 0
			return 0
		else
			return self.reviews.sum(:rating)/self.reviews.size
		end
	end
end

app/models/refrigerated_ice_cream.rb
class Refrigerating < ActiveRecord::Base
	validates :ice_cream_id, :nice_box_id, presence: true

	belongs_to :ice_cream
	belongs_to :nice_box
end

app/models/refrigerating.rb
class Refrigerating < ActiveRecord::Base
	validates :ice_cream_id, :user_id, presence: true
	validates_uniqueness_of :ice_cream_id, :scope => [:user_id]

	belongs_to :ice_cream
	belongs_to :user
end

app/models/review.rb
class Review < ActiveRecord::Base
	validates :ice_cream_id, :user_id, :rating, presence: true
	validates_uniqueness_of :ice_cream_id, :scope => [:user_id]

	belongs_to :user
	belongs_to :ice_cream

end

app/models/user.rb
class User < ActiveRecord::Base

  validates :username, :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password

  has_many :reviews
  has_many(
    :reviewed_ice_creams,
    through: :reviews,
    source: :ice_cream
  )

  has_many :refrigeratings

  has_many(
    :refrigerated_ice_creams,
    through: :refrigeratings,
    source: :ice_cream
  )

  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user && user.valid_password?(password)
    user
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

end

app/controllers/api/api_controller.rb
module Api
  class ApiController < ApplicationController
    # before_action :require_signed_in!

    # def require_board_member!
    #   redirect_to new_session_url unless current_board.is_member?(current_user)
    # end
  end
end

app/controllers/api/reviews_controller.rb
module Api
	class ReviewsController < ApiController

		def create
			@review = Review.new(review_params)
			# @review = current_ice_cream.reviews.new(review_params)
			# @review.user_id = current_user.id
			if @review.save
				render json: @review
			else
				render json: @review.errors.full_messages, status: :unprocessable_entity
			end
		end

		private

		def review_params
			params.require(:review).permit(:rating, :content, :user_id, :ice_cream_id)
		end

	end
end

app/controllers/api/users_controller.rb
module Api
	class UsersController < ApiController

		def index
			@users = User.all
			render json: @users
		end

		def update
	    @user = User.find(params[:id]) 
	    if @user.update(user_params)
	      render json: @user
	    else
	      render json: @user.errors.full_messages, status: :unprocessable_entity
	    end
	  end

		def show
			@user = User.includes(:reviews, :reviewed_ice_creams, :refrigerated_ice_creams).find(params[:id])
			render :show
		end

		private
		def user_params
	    params.require(:user).permit(:password, :username, :avatar_url)
	  end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead

  #protect_from_forgery with: :exception

  # Expose these methods to the views
  helper_method :current_user, :signed_in?

  private
  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in(user)
    @current_user = user
    session[:session_token] = user.reset_token!
  end

  def sign_out
    current_user.try(:reset_token!)
    session[:session_token] = nil
  end

  def require_signed_in!
    redirect_to new_session_url unless signed_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end


  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user
      sign_in(user)
      redirect_to root_url
    else
      flash[:errors] = ["Invalid username or password"]
      redirect_to ""
    end
  end

  def destroy
    sign_out
    redirect_to ""
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def root
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params) 
    if @user.save
      sign_in(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:password, :username, :avatar_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ice_boxes_helper.rb
module IceBoxesHelper
end

app/helpers/ice_creams_helper.rb
module IceCreamsHelper
end

app/helpers/refregiratings_helper.rb
module RefregiratingsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<%= flash[:errors].join("<br>").html_safe if flash[:errors] %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top special-navbar" role="navigation">
<div class="container fix-width">
  <div class="navbar-header">
    <a class="navbar-brand" href="#">NiceCream</a>
  </div>

  <div class="fix-width" id="bs-example-navbar-collapse-1">
    <form class="navbar-form navbar-left" role="search" id="search">
        <input type="text" class="form-control rounded-corners typeahead" placeholder="Search">
        <input type="submit" value="Search" class="not-button">
    </form>
    <% if signed_in? %>
      <ul class="nav navbar-nav">
          <li><a href="/#">flavors</a></li>
          <li><a href="/#home">me</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-form">
  <!--       <li id='add-dropdown' class='dropdown'>
          <button 
            class='dropdown-toggle navbar-btn btn btn-primary'
            data-toggle='dropdown'><span class='glyphicon glyphicon-plus'></span>
          </button>
        </li> -->
        <li><%= button_to "Out", session_url, method: :delete, class: "not-button" %></li>
      <ul>
    <% else %>
      <div class="nav navbar-nav navbar-form">
        <li><%= render partial: "layouts/sessionform" %></li>
        <li> <button id="guest-login" type="submit" class="not-button rounded-corners">
          Guest login </button></li>
        <li><%= link_to "New?", new_user_url %></li>
      </div>
  <% end %>
  </div>
</div>
</nav>

<% if flash[:errors] %>
<div class="alert alert-warning alert-dismissible" role="alert">
   <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
<%= flash[:errors].join("<br>").html_safe %>
</div>
<% end %>

app/views/layouts/_sessionform.html.erb
<form action="<%= session_url %>" method="post">

  <label>
    Username
    <input id="user-name" class="rounded-corners" type="text" name="user[username]" value="">
  </label>
  <br>
  <label>
    Password
    <input id="pass-word" class="rounded-corners" type="password" name="user[password]" value="">
  </label>

  <button id="sign-in" type="submit" class="not-button rounded-corners">
    Sign in</button>
</form>
<%= render "layouts/errors" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NiceCreams</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script type="text/javascript" src="//api.filepicker.io/v1/filepicker.js"></script>
  <%= csrf_meta_tags %>

  <script>
    filepicker.setKey("AZFWUwDTpmgQMlO9qN2cgz"); 
  </script>
</head>
<body>

<%= render partial: "layouts/header" %>

<%= yield %>


 <script>
   	$("button#guest-login").on("click", function(){
			$('#user-name').val('guest');
			$('#pass-word').val('password');
			$('#sign-in').click();
  	})
  </script>

</body>
</html>